ALTER TABLE IF EXISTS person DROP CONSTRAINT fk_city;

ALTER TABLE IF EXISTS person RENAME COLUMN city_id TO city;

ALTER TABLE IF EXISTS person ALTER COLUMN city TYPE VARCHAR(255);

ALTER TABLE IF EXISTS person ADD COLUMN country VARCHAR(255);
