server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/postgres
        username: anton
        password:
    liquibase:
        enabled: true

logging:
    level:
        root: info
    profiles:
        active: prod

yandex-profile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY

logs-upload:
    enabled: false

mailing-service:
    email: javaproteams27@yandex.ru

register-service:
    default-photo: /c55aeb2a-6100-48e6-a006-0cec9f913b38.jpg

redis:
    url: redis://127.0.0.1:6379
    enabled: true